### PR TITLE
Remove prints

### PR DESCRIPTION
**Pull request by larsyunker**
Fixed a couple of annoying but non-critical bugs. 
- the open file in `AgilentCSDAD2` is now closed after data processing is complete 
- the print statements from the `AgilentMS.old_data` property have been commented out. In PyCharm when debugging, properties are frequently updated for namespace inspection and this resulted in a _lot_ of prints to console 
- incremented version to 0.7.1 to indicate changes on pypi

### CODE REVIEW

**Comment by bovee** [comment]
Thanks! The first two commits on this look like they're forked versions of the ones that have already landed so it's saying this PR can't be rebased in safely? There's also no PR #1 on the third commit? I think maybe an interactive rebase to drop those would fix that.

Also, as a heads up, I've been playing around writing an alternate parser for some of these file formats; the output is a little different and I'm not sure how easy it is to install (especially the python bindings), but just in case it might be useful: https://github.com/bovee/entab

**Comment by larsyunker** [comment]
Ok I'll try to sort out the conflicts. Sorry, I usually use Gitlab and I'm new to forking and contributing. I tried to pull request to update my fork and I probably did it wrong.

I'll also check out the link. I assume that it is more efficient at processing? That would be quite helpful for batch processing which I've found can be quite slow. 

I have some other suggestions for changes but I'll make separate issues for those for discussion.

**Comment by bovee** [comment]
No problems! And I'm happy to take any suggestions or changes and pin a new release.

The Python bindings for entab may be a little faster (haven't benchmarked much, but maybe 10%?) and hopefully it's a bit better written, tested, and more maintainable. It's more of a personal, experimental project for me right now, but I'm happy to incorporate any feedback that might make it more useful for others.

**Comment by larsyunker** [comment]
Ok I definitely bumbled my way through that, but I think I finally managed to properly rebase my fork. How does this look?

**Comment by bovee** [comment]
Great! Thanks!

**Comment by bovee** [comment]
Just pushed the new version up to PyPI.

**Pull request merged**
